[package]

name = "rustless"
version = "0.1.3"
authors = ["Stanislav Panferov <fnight.m@gmail.com>"]
description = "Rustless is a REST-like API micro-framework for Rust."
keywords = ["api", "web", "hyper", "iron", "rest"]
readme = "README.md"
license = "MIT"

[lib]
name = "rustless"
path = "src/lib.rs"

[[test]]
name = "tests"

[dependencies]
regex = "*"
rustc-serialize = "*"
valico = "*"
queryst = "*"
jsonway = "*"
url = "*"
error = "*"
cookie = "*"
hyper = "*"
iron = "*"